[package]
name = "rust_keka_chromium"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
chromiumoxide = "0.3.1"
async-std = "1.10.0"
dirs = "4.0"
